services:

  spadmin:
    container_name: spadmin
    hostname: spadmin
    #    restart: always
    image: ubuntu/dsmc:20230401
    build: .

    stdin_open: true 
    tty: true

    ports:
      - "2222:22"

    environment:
      - DEBUG=false

    volumes:
      - /root/spadmin_build/spadmin_runtime/dsm.opt:/opt/tivoli/tsm/client/ba/bin/dsm.opt:ro
      - /root/spadmin_build/spadmin_runtime/dsm.sys:/opt/tivoli/tsm/client/ba/bin/dsm.sys:ro
      - /root/spadmin_build/spadmin_runtime/authorized_keys:/root/.ssh/authorized_keys:ro
      - /root/spadmin_build/spadmin_runtime/bash_login:/root/.bash_login:ro
      - /root/spadmin_build/spadmin_runtime/spadmin_run:/usr/local/bin/spadmin:ro

      - /root/spadmin/.spadmin_history:/root/.spadmin_history

      - /root/spadmin/.config/:/root/.config/

      # - /root/spadmin/:/root/spadmin/

    command: ["/usr/sbin/sshd", "-D"]

